# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Tlend' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'XLPagerTabStrip', '~> 8.1.0'

  # Pods for Tlend
  pod 'Kingfisher'
  pod 'SnapKit'
  
  pod 'KeychainAccess'
  pod 'Alamofire'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxKeyboard'
  
  pod 'MMPlayerView', '~> 4.1.3'
end
